apiVersion: apps/v1
kind: Deployment
metadata:
  name: blt-health
  labels:
    app: blt-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blt-health
  template:
    metadata:
      labels:
        app: blt-health
    spec:
      containers:
        - name: blt-health
          image: minerva45/blt-health:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: blt-health-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: blt-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blt-db-credentials
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
